# Generated by Django 3.1.2 on 2020-10-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgID', models.CharField(max_length=200)),
                ('orgName', models.CharField(max_length=200)),
                ('orgURL', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(max_length=200)),
                ('netName', models.CharField(max_length=200)),
                ('orgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
        ),
    ]
