# Generated by Django 3.1.2 on 2020-11-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgID', models.CharField(max_length=200)),
                ('orgName', models.CharField(max_length=200)),
                ('orgURL', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(default=None, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(max_length=200)),
                ('netName', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', unique=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devAddr', models.CharField(max_length=200)),
                ('devSerial', models.CharField(max_length=200)),
                ('devMac', models.CharField(max_length=200)),
                ('devModel', models.CharField(max_length=200)),
                ('devLat', models.FloatField()),
                ('devLong', models.FloatField()),
                ('slug', models.SlugField(default='', unique=True)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.network')),
            ],
        ),
    ]
