# Generated by Django 3.1.2 on 2020-11-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(default='6bec40cf957de430a6f1f2baa056b99a4fac9ea0', max_length=128),
        ),
    ]
