# Generated by Django 3.1.2 on 2021-01-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='netID',
            new_name='net_id',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='netName',
            new_name='net_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgID',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgName',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgURL',
            new_name='org_url',
        ),
    ]
