# Generated by Django 3.1.2 on 2020-10-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='orgID',
            new_name='org',
        ),
    ]
