<<<<<<< HEAD:cisco_dashboard/main/migrations/0002_auto_20210305_1530.py
# Generated by Django 3.1.2 on 2021-03-05 15:30
=======
# Generated by Django 3.1.2 on 2021-02-24 00:21
>>>>>>> origin:cisco_dashboard/main/migrations/0002_auto_20210224_0021.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='netID',
            new_name='net_id',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='netName',
            new_name='net_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgID',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgName',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgURL',
            new_name='org_url',
        ),
        migrations.AlterField(
            model_name='network',
            name='scanningAPIURL',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
