# Generated by Django 3.1.2 on 2021-03-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='netID',
            new_name='net_id',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='netName',
            new_name='net_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgID',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgName',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='orgURL',
            new_name='org_url',
        ),
        migrations.AlterField(
            model_name='network',
            name='scanningAPIURL',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organisation')),
            ],
        ),
    ]
