# Generated by Django 3.1.2 on 2021-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accessalert_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessalert',
            name='distance',
            field=models.CharField(default=0.1, max_length=10),
        ),
    ]
