# Generated by Django 3.1.2 on 2020-10-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201025_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
