# Generated by Django 3.1.2 on 2021-03-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210310_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.device'),
            preserve_default=False,
        ),
    ]
