# Generated by Django 3.1.2 on 2020-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201129_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
