# Generated by Django 3.1.2 on 2021-03-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210224_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='user',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='org',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.organisation'),
            preserve_default=False,
        ),
    ]
