# Generated by Django 3.1.2 on 2020-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201025_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='orgAPIOverview',
            field=models.JSONField(default=list),
        ),
    ]
