# Generated by Django 3.1.2 on 2020-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201129_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='apikey',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
