# Generated by Django 3.1.2 on 2021-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_network_scanningapiurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='scanningAPIURL',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
