# Generated by Django 3.1.2 on 2020-11-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201025_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devName', models.CharField(max_length=200)),
                ('devNotes', models.CharField(max_length=200)),
                ('devAddr', models.CharField(max_length=200)),
                ('devSerial', models.CharField(max_length=200)),
                ('devMac', models.CharField(max_length=200)),
                ('devModel', models.CharField(max_length=200)),
                ('devLanIP', models.CharField(max_length=200)),
                ('devLat', models.FloatField()),
                ('devLong', models.FloatField()),
                ('slug', models.SlugField(default='', unique=True)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.network')),
            ],
        ),
    ]
