# Generated by Django 3.1.2 on 2020-11-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='devLanIP',
        ),
    ]
