# Generated by Django 3.1.3 on 2020-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
