# Generated by Django 3.1.3 on 2020-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='apikey',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
