# Generated by Django 3.1.2 on 2021-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='scanningAPIURL',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
