# Generated by Django 3.1.2 on 2020-11-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_device_devlanip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='devName',
        ),
        migrations.RemoveField(
            model_name='device',
            name='devNotes',
        ),
    ]
