# Generated by Django 3.1.2 on 2020-11-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201104_1607'),
        ('main', '0005_remove_organisation_orgapioverview'),
    ]

    operations = [
    ]
