stages:
  - tests


test:code_quality:
    stage: tests
    image: python:3.7
    tags:
        - docker
        
    script:
        - cd cisco_dashboard/main
        
        - pip3 install django
        - pip3 install pylint
        - pip3 install meraki
        
        #The --disable=W0222 flag is required due to Django formatting
        - pylint --disable=W0222 models.py -r y # Checks that models.py is correctly formatted
        
        #The --disable=R0903 flag is required due to Django formatting
        - pylint --disable=R0903 forms.py -r y  # Checks that forms.py is correctly formatted
        
        #The --disable=E1101 flag is required due to Django formatting -  E1101: Class 'Organisation' has no 'objects' member (no-member)
        - pylint --disable=E1101 tests.py -r y  # Checks that tests.py is correctly formatted
        
        #The --disable=E1101 flag is again required due to Django formatting
        - pylint --disable=E1101 views.py -r y  # Checks that views.py is correctly formatted
    

test:unit_tests:
    stage: tests
    image: python:3.7
    tags:
        - docker
    
    script:
        - cd cisco_dashboard
    
        # Create environment for python
        - pip3 install virtualenv
        - virtualenv -p python3 venv
        - source venv/bin/activate
        - pip3 install -r requirements.txt
        - pip3 install coverage
        
        # Set up and run tests
        - python3 manage.py makemigrations 
        - python3 manage.py migrate
        - python3 manage.py test
        - coverage run ./manage.py test --noinput && coverage report

